
version: '3'

services:
  changedetection:
    image: dgtlmoon/changedetection.io
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - WEBDRIVER_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium
    volumes:
      - changedetection-data:/datastore
    restart: always

  selenium:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    environment:
      - STARTUP_TIMEOUT=60  # увеличьте тайм-аут для WebDriver
    restart: always

volumes:
  changedetection-data:
